baseURL = 'https://zanders.cloud/'
languageCode = 'en-us'
title = 'zanders.cloud'
theme = 'hugo-theme-shell'

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "Zander Havgaard's website"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  # Note: If you want to use the Goph theme, set it to "goph" (See README.md)
  schema = "One Dark"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "zander"
  pcName = "nostromo"
  workDir = "zanders.cloud"
  profile = "index.md"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 1 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  # Note:
  # Note: if you want to enable Mathjax, you need to set it to 0
  # Note: and set "math: true" at front matter in your Markdown file
  titleDelay = 0 # title speed : "title" in front matter
  contentDelay = 0 # content speed : content in .md file

  description = """

# Zander Havgaard
-----------------

* I'm a DevOps & Cloud Native consultant
with @eficode in Copenhagen 🏙

* I love teaching and I'm a trainer for a
number of courses in kubernetes, docker
and other Cloud Native technologies 🧑‍🏫

* I'm excited about everything DevOps,
Cloud Native, CI/CD, IaC, Public Cloud,
Containerization, FaaS, Serverless etc. ☁

* I'm a big fan of FOSS, Linux,
tiling WMs and NeoVim ❤

## Getting in Touch

I don't use social media, so the
best way to reach me is to send an
email to `contact (at) pzh (dot) dk` 📫

  """
  # description = "/description.md"

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "symlinks"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [
    ["github", "https://github.com/zanderhavgaard"],
    ["dotfiles", "https://github.com/zanderhavgaard/dotfiles"],
    ["neovim-config", "https://github.com/zanderhavgaard/neovim-config"],
  ]
