---
version: "3"

tasks:
  submodule-init:
    cmds:
      - git submodule update --init --recursive

  serve:
    cmds:
      - zola serve
      - firefox "http://localhost:8080"

  build-docker:
    cmds:
      - docker build -t "zanders.cloud:local" .

  run-docker-local:
    cmds:
      - docker run --rm -it -p 8080:80 -t "zanders.cloud:local"

  run-docker-local-shell:
    cmds:
      - docker run --rm -it --entrypoint sh "zanders.cloud:local"
